security:
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: true
        
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        api:
            anonymous: true
            pattern: ^/api/
            stateless: true
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
                    - App\Security\LoginApiAuthenticator
            entry_point: App\Security\TokenAuthenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            form_login: true
            logout:
                path:   app_logout
       
    access_control:
        - { path: ^/api/snippets, roles: ROLE_USER}
        - { path: ^/api/snippet, roles: ROLE_USER}
        - { path: ^/api/refresh, roles: ROLE_USER}
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/snippets/list, roles: [ROLE_USER, ROLE_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/snippets/detail, roles: [ROLE_USER, ROLE_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/snippets, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/change, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/admin, roles: ROLE_ADMIN }