version: '2'

services:

    mysql:
        container_name: snippets_mysql
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - snippets_db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        container_name: snippets_php
        build:
            context: php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${DOCKER_APP_PATH}:/var/www:cached
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        container_name: snippets_nginx
        build: nginx
        ports:
            - 8080:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
            
volumes:
    snippets_db:
