#index:
#    path: /
#    controller: App\Controller\DefaultController::index

confirmation:
    path: /confirm/user={userId}/token={confirmToken}
    controller: App\Controller\ConfirmationController::confirm
